from datetime import timedelta
from typing import Protocol, TypeVar

from app.dto import ChatContext, UserContext

T = TypeVar("T")


class CacheClient(Protocol):
    async def get(self, key: str) -> bytes | str | None: ...
    async def set(self, key: str, value: str | bytes | int | float, expire: int | timedelta | None = None) -> None: ...
    async def delete(self, key: str) -> None: ...
    async def exists(self, key: str) -> bool: ...
    async def warmup(self) -> None: ...


class CacheRepo[T](Protocol):
    async def get_by_id(self, tg_id: int) -> T | None: ...
    async def set(self, context: T, ttl: int | timedelta | None = None) -> None: ...
    async def invalidate(self, tg_id: int) -> None: ...


class CacheRepoRegistry(Protocol):
    @property
    def users(self) -> CacheRepo[UserContext]: ...
    @property
    def chats(self) -> CacheRepo[ChatContext]: ...
    async def warmup(self) -> None: ...
