from datetime import timedelta
from typing import Protocol, TypeVar

from app.dto import ChatContext, UserContext
from domain.chat import Chat
from domain.user import User

T = TypeVar("T")
V = TypeVar("V")


class CacheClient(Protocol):
    async def get(self, key: str) -> bytes | str | None: ...
    async def set(self, key: str, value: str | bytes | int | float, expire: int | timedelta | None = None) -> None: ...
    async def delete(self, key: str) -> None: ...
    async def exists(self, key: str) -> bool: ...


class CacheRepo[T, V](Protocol):
    async def get_by_id(self, tg_id: int) -> T | None: ...
    async def set(self, entity: V, ttl: int | timedelta | None = None) -> None: ...
    async def invalidate(self, tg_id: int) -> None: ...


class CacheRepoRegistry(Protocol):
    @property
    def user(self) -> CacheRepo[UserContext, User]: ...
    @property
    def chat(self) -> CacheRepo[ChatContext, Chat]: ...
