"""Application layer errors."""

from .application import ChatNotFoundError, UserNotFoundError
from .base import AppError, UnexpectedAppError
from .network import (
    HttpAuthError,
    HttpError,
    HttpRequestError,
    HttpResponseError,
    HttpTimeoutError,
    HttpTransportError,
    UnexpectedHttpError,
)
from .observe import LoggingError, LogMessageFormatError, MetricsError, MetricsExportError, MetricsHttpExporterError
from .persistence import (
    AggregateMappingError,
    CacheBackendError,
    CacheError,
    CacheTimeoutError,
    CacheUnavailableError,
    CatalogError,
    CatalogFormatError,
    CatalogNotFoundError,
    CatalogParseError,
    DataIntegrityError,
    DBError,
    RepositoryError,
    UnexpectedCacheError,
    UnexpectedCatalogError,
    UnexpectedDBError,
)
from .resilience import (
    CircuitError,
    CircuitOpenError,
    CircuitStorageError,
    LimitError,
    LimitStorageError,
    MaxAttemptsExhaustedError,
    RetryError,
    TooManyRequests,
    UnexpectedCircuitError,
    UnexpectedLimitError,
    UnexpectedRetryError,
)
from .utils import unwrap_exception

__all__ = [
    "AggregateMappingError",
    "AppError",
    "CacheBackendError",
    "CacheError",
    "CacheTimeoutError",
    "CacheUnavailableError",
    "CatalogError",
    "CatalogFormatError",
    "CatalogNotFoundError",
    "CatalogParseError",
    "ChatNotFoundError",
    "CircuitError",
    "CircuitOpenError",
    "CircuitStorageError",
    "DBError",
    "DataIntegrityError",
    "HttpAuthError",
    "HttpError",
    "HttpRequestError",
    "HttpResponseError",
    "HttpTimeoutError",
    "HttpTransportError",
    "LimitError",
    "LimitStorageError",
    "LogMessageFormatError",
    "LoggingError",
    "MaxAttemptsExhaustedError",
    "MetricsError",
    "MetricsExportError",
    "MetricsHttpExporterError",
    "RepositoryError",
    "RetryError",
    "TooManyRequests",
    "UnexpectedAppError",
    "UnexpectedCacheError",
    "UnexpectedCatalogError",
    "UnexpectedCircuitError",
    "UnexpectedDBError",
    "UnexpectedHttpError",
    "UnexpectedLimitError",
    "UnexpectedRetryError",
    "UserNotFoundError",
    "unwrap_exception",
]
