name: Lint Check

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

permissions:
  contents: read

jobs:
  ruff-lint:
    runs-on: ubuntu-latest
    env:
      POETRY_VERSION: "1.8.4"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: "poetry"

      - name: Install Poetry
        run: pipx install "poetry==${POETRY_VERSION}"

      - name: Install dependencies
        run: |
          poetry install --with dev --no-interaction

      - name: Run ruff lint
        run: make lint
