name: Lint Check

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

permissions:
  contents: read

jobs:
  ruff-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python and uv
        uses: ./.github/actions/setup-python-uv
        with:
          python-version: ${{ inputs.python-version }}

      - name: Run ruff lint
        run: make lint
